/* maps .c */
#include "mapping.h"

int map[MAP_ROWS][MAP_ROWS] = {
{WA_L  ,  WA_L ,  WA_L ,  WA_L ,  WA_L ,  WA_L ,  WA_L ,  WA_L ,  WA_L ,  WA_L,    WA_L,   WA_L,   WA_L},  
{WA_L  ,  SPACE,  HOLE ,  SPACE,  WA_L ,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  WA_L ,  ROCK ,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  WA_L ,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  WA_L ,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  WA_L ,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  WA_L ,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  WA_L ,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  HOLE ,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  SPACE,  ROCK ,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,  SPACE,   SPACE,  SPACE,  WA_L},  
{WA_L  ,  WA_L ,  WA_L , WA_L  ,  WA_L ,  WA_L ,  WA_L ,  WA_L ,  WA_L ,  WA_L ,   WA_L ,  WA_L ,  WA_L}
};